apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-user
  labels:
    app: us-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: us-user
  template:
    metadata:
      labels:
        app: us-user
    spec:
      containers:
      - name: us-user
        image: 76591745/user:v1
        ports:
        - containerPort: 8084
      restartPolicy: Always